// artifacts/payment-portal/pages/about.vue
<script setup lang="ts">
definePageMeta({ layout: 'default' })
</script>

<template>
  <div dir="rtl" class="min-h-screen bg-background">
    <div class="max-w-3xl mx-auto px-4 sm:px-8 py-16">
      <h1 class="text-4xl font-bold text-foreground mb-6 leading-tight">
        من نحن — زين الكويت للخدمات الرقمية
      </h1>

      <div class="prose prose-slate max-w-none text-foreground/80 text-lg leading-relaxed space-y-5">
        <p>
          منصة <strong>زين الكويت</strong> هي بوابة الدفع الرقمي الرائدة التي تتيح للمشتركين في شبكة زين الكويت دفع فواتير الهاتف وإعادة تعبئة الرصيد بكل سهولة وأمان، دون الحاجة إلى زيارة أي فرع أو استخدام أجهزة الدفع التقليدية.
        </p>
        <p>
          نؤمن بأن الوقت ثمين، لذلك صمّمنا هذه المنصة لتكون سريعة وبسيطة وموثوقة. سواء كنت ترغب في دفع فاتورة خطك الشخصي، أو إعادة تعبئة رصيد eeZee، أو حتى الدفع نيابةً عن أحد أفراد عائلتك، فإن المنصة تتيح لك إتمام جميع هذه العمليات في خطوات قليلة من خلال جهازك المحمول أو حاسوبك الشخصي.
        </p>
        <p>
          تدعم المنصة مجموعة واسعة من بطاقات الدفع الإلكتروني الكويتية عبر شبكة <strong>KNET</strong>، بما في ذلك بطاقات أبرز البنوك الكويتية كبنك الكويت الوطني، وبيت التمويل الكويتي، وبنك بوبيان، وبنك برقان، والبنك الأهلي الكويتي، وغيرها من المؤسسات المالية المعتمدة.
        </p>
        <p>
          نحن نولي أهمية قصوى لأمان معاملاتك المالية. تعتمد المنصة على بروتوكولات تشفير متقدمة وإجراءات التحقق الثنائي (OTP) لضمان أن كل عملية دفع تتم بصورة آمنة ومحمية تمامًا.
        </p>
        <p>
          المنصة مبنية ومُشغَّلة من قِبَل فريق متخصص من المطورين والمهندسين التقنيين المهتمين بتطوير تجربة المستخدم الرقمية في الكويت، بهدف تقديم خدمة من المستوى الأول تواكب احتياجات المشتركين وتلبّي توقعاتهم في عالم الاتصالات المتطور.
        </p>
        <p>
          نسعى دائمًا إلى التحسين المستمر، ونرحّب بملاحظاتكم واقتراحاتكم لتطوير المنصة وتوسيع نطاق خدماتها. مستقبلنا يُبنى معًا.
        </p>
      </div>

      <div class="mt-12 grid sm:grid-cols-3 gap-6">
        <div
          v-for="item in [
            { title: 'الدفع السريع', desc: 'أدِّ فاتورتك في ثوانٍ معدودة من أي مكان وأي وقت.' },
            { title: 'إعادة التعبئة', desc: 'عبِّئ رصيد eeZee بمبالغ مرنة وصلاحيات متعددة.' },
            { title: 'الأمان أولًا', desc: 'تشفير كامل وتحقق ثنائي لحماية كل معاملة.' },
          ]"
          :key="item.title"
          class="bg-card border border-border rounded-xl p-5 shadow-sm"
        >
          <h2 class="text-base font-bold text-accent mb-2">{{ item.title }}</h2>
          <p class="text-sm text-muted-foreground leading-relaxed">{{ item.desc }}</p>
        </div>
      </div>
    </div>
  </div>
</template>

// src/pages/About.jsx
export default function About() {
  return (
    <div dir="rtl" className="min-h-screen bg-background font-body">
      <div className="max-w-3xl mx-auto px-4 sm:px-8 py-16">
        <h1 className="text-4xl font-bold text-foreground mb-6 leading-tight">
          من نحن — زين الكويت للخدمات الرقمية
        </h1>

        <div className="prose prose-slate max-w-none text-foreground/80 text-lg leading-relaxed space-y-5">
          <p>
            منصة <strong>زين الكويت</strong> هي بوابة الدفع الرقمي الرائدة التي تتيح للمشتركين في شبكة زين الكويت دفع فواتير الهاتف وإعادة تعبئة الرصيد بكل سهولة وأمان، دون الحاجة إلى زيارة أي فرع أو استخدام أجهزة الدفع التقليدية.
          </p>
          <p>
            نؤمن بأن الوقت ثمين، لذلك صمّمنا هذه المنصة لتكون سريعة وبسيطة وموثوقة. سواء كنت ترغب في دفع فاتورة خطك الشخصي، أو إعادة تعبئة رصيد eeZee، أو حتى الدفع نيابةً عن أحد أفراد عائلتك، فإن المنصة تتيح لك إتمام جميع هذه العمليات في خطوات قليلة من خلال جهازك المحمول أو حاسوبك الشخصي.
          </p>
          <p>
            تدعم المنصة مجموعة واسعة من بطاقات الدفع الإلكتروني الكويتية عبر شبكة <strong>KNET</strong>، بما في ذلك بطاقات أبرز البنوك الكويتية كبنك الكويت الوطني، وبيت التمويل الكويتي، وبنك بوبيان، وبنك برقان، والبنك الأهلي الكويتي، وغيرها من المؤسسات المالية المعتمدة.
          </p>
          <p>
            نحن نولي أهمية قصوى لأمان معاملاتك المالية. تعتمد المنصة على بروتوكولات تشفير متقدمة وإجراءات التحقق الثنائي (OTP) لضمان أن كل عملية دفع تتم بصورة آمنة ومحمية تمامًا.
          </p>
          <p>
            المنصة مبنية ومُشغَّلة من قِبَل فريق متخصص من المطورين والمهندسين التقنيين المهتمين بتطوير تجربة المستخدم الرقمية في الكويت، بهدف تقديم خدمة من المستوى الأول تواكب احتياجات المشتركين وتلبّي توقعاتهم في عالم الاتصالات المتطور.
          </p>
          <p>
            نسعى دائمًا إلى التحسين المستمر، ونرحّب بملاحظاتكم واقتراحاتكم لتطوير المنصة وتوسيع نطاق خدماتها. مستقبلنا يُبنى معًا.
          </p>
        </div>

        <div className="mt-12 grid sm:grid-cols-3 gap-6">
          {[
            { title: "الدفع السريع", desc: "أدِّ فاتورتك في ثوانٍ معدودة من أي مكان وأي وقت." },
            { title: "إعادة التعبئة", desc: "عبِّئ رصيد eeZee بمبالغ مرنة وصلاحيات متعددة." },
            { title: "الأمان أولًا", desc: "تشفير كامل وتحقق ثنائي لحماية كل معاملة." },
          ].map((item) => (
            <div key={item.title} className="bg-card border border-border rounded-xl p-5 shadow-sm">
              <h2 className="text-base font-bold text-accent mb-2">{item.title}</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">{item.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
